In [7]:
import torch
import torch.nn as nn
import math

m = nn.BatchNorm1d(7)
input = torch.randn(3, 7,2)*20
print(input)
output = m(input)
print(output)

tensor([[[ 30.3290, -16.1564],
         [-13.0467,  -3.1977],
         [ 18.3903, -45.1024],
         [-25.3257, -10.4570],
         [  4.7485,   3.1183],
         [ -0.4047, -22.6060],
         [-16.4971,   1.7927]],

        [[-17.7500,  -2.2375],
         [  8.8722,  17.2850],
         [ 10.8726,  12.5430],
         [  8.3509, -10.7708],
         [ 23.3328, -17.4307],
         [-19.3110, -26.9061],
         [  6.1153,  33.5117]],

        [[-38.5411, -19.1678],
         [ 21.0413, -12.1367],
         [ 12.2750,  28.4303],
         [-10.4217, -20.9771],
         [-18.2784,  21.8331],
         [ 27.0344,  10.6377],
         [ 29.0488,   1.3745]]])
tensor([[[ 1.9356, -0.2634],
         [-1.2012, -0.4702],
         [ 0.5126, -2.1650],
         [-1.2914,  0.1076],
         [ 0.1125,  0.0140],
         [ 0.2487, -0.8887],
         [-1.4971, -0.4326]],

        [[-0.3388,  0.3950],
         [ 0.4258,  1.0502],
         [ 0.1956,  0.2660],
         [ 1.8772,  0.0780],
         [ 1.2362, -1.

In [8]:
instance_weights = torch.as_tensor(torch.rand(10, 20), device = 'cuda')
instance_weights.shape

torch.Size([10, 20])

In [9]:
import numpy as np

val,idx = instance_weights.topk(int(math.ceil(0.2*20)))
val

nomask = np.random.random([2,2])
indices = [[True,False],[True,False]]

nomask,nomask[indices]

(array([[0.46101799, 0.50614888],
        [0.2327638 , 0.51958237]]),
 array([0.46101799, 0.2327638 ]))

In [11]:
y = np.random.uniform(1,10,20)
y[21:24]

array([], dtype=float64)